# This is a basic workflow that is manually triggered

name: Docker multiarch build python with requests

on:
  workflow_dispatch:
    # Inputs the workflow accepts.

env:
  TEST_PYTHON: python:test

jobs:

  build-python:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Get Python version used in image tags
        run: |
          docker build -t $TEST_PYTHON -f Dockerfile .
          VERSION=$(docker run $TEST_PYTHON python3 -V | sed 's/Python //')
          image_name=ghcr.io/${{ github.repository_owner }}/python
          echo "tags=${image_name}:${VERSION},${image_name}:latest" >> ${GITHUB_ENV}
          echo "VERSION=${VERSION}" >> ${GITHUB_ENV}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: ghcr.io/${{ github.repository_owner }}/python:${{ env.VERSION }}
        run: echo "${{ env.tags }}"
      
      - name: Build and push image python:${{ env.VERSION }}
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: ${{ env.tags }}
